plugin: google.cloud.gcp_compute # specify the plugin in use
zones: # zones in which to find VMs
  - us-east1-b
projects: # projects for which to find VMs
  - {{ GCP_PROJECT }}
filters:
  - status = RUNNING
  - scheduling.automaticRestart = true AND status = RUNNING
auth_kind: application # use GOOGLE_APPLICATION_CREDENTIALS for auth
scopes:
  - 'https://www.googleapis.com/auth/cloud-platform'
  - 'https://www.googleapis.com/auth/compute.readonly'
keyed_groups: # create inventory host groups based on VM labels
  - prefix: gcp
    key: labels
name_suffix: .qa.com # this and next section define display name format: <vm_name>.qa.com
hostnames:
  - name
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP # set the actual hostnames used for SSH to be the VMs public IPs